name: Code Linting

on:
  push: # Comment this line to trigger action only on pull-requests (not recommended if you don't pay for GH Actions)
    paths:
      - "**.py"
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
  workflow_dispatch:

jobs:
  code_styling:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        run: |
          pip install black isort mypy pylint
      - name: Run Black
        run: black . --check
      - name: Run iSort
        run: isort . --check-only
      - name: Run MyPy
        run: mypy dominion --show-error-codes
      - name: Run PyLint
        run: pylint dominion